version: '3'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    volumes:
      - /var/lib/postgresql
    ports:
      - 5432:5432/tcp
    shm_size: 4GB
    environment:
      - POSTGRES_PASSWORD=password

  crawler:
    build: ./
    volumes:
      - ./data:/data
    ports:
      - 30303:30303/udp  # Discovery
      - 30303:30303/tcp  # Eth listener
      - 9191:9191/tcp    # Metrics
    command:
      - crawl
      - --crawler-db
      - /data/crawler.db
      # Make sure you have the GeoLite DB in the ./data directory.
      # Comment out the following two lines to disable the GeoLite DB.
      - --geoipdb
      - /data/GeoLite2-City.mmdb

  api:
    build: ./
    volumes:
      - ./data:/data
    ports:
      - 10000:10000/tcp  # HTTP port
      - 9192:9191/tcp    # Metrics
    depends_on:
      - crawler
    command: 
      - api
      - --crawler-db
      - /data/crawler.db
      - --enode
      - "enode://asdf1234...@example.com:30303"
